export const KNOWN_SSML_TAGS: ReadonlyArray<string> = [
  "speak",
  "voice",
  "prosody",
  "emphasis",
  "break",
  "sub",
  "phoneme",
  "say-as",
  "audio",
  "p",
  "s",
  "lang",
  "mark",
  "bookmark",
  "lexicon",
  "math",
  "mstts:audioduration",
  "mstts:backgroundaudio",
  "mstts:voiceconversion",
  "mstts:ttsembedding",
  "mstts:embedding",
  "mstts:express-as",
  "mstts:silence",
  "mstts:viseme",
  "par",
  "seq",
  "media",
  "desc",
  "amazon:domain",
  "amazon:effect",
  "amazon:emotion",
  "amazon:auto-breaths",
  "sentence",
  "lookup",
  "token",
  "w",
];

export const TEXT_ONLY_SSML_TAGS: ReadonlyArray<string> = [
  "phoneme",
  "say-as",
  "sub",
];

export const SELF_CONTAINED_SSML_TAGS: ReadonlyArray<string> = [
  "bookmark",
  "break",
  "lexicon",
  "mark",
  "mstts:audioduration",
  "mstts:backgroundaudio",
  "mstts:voiceconversion",
  "mstts:silence",
  "mstts:viseme",
];
