name: Publish Packages

on:
  push:
    tags:
      - "v*"

jobs:
  publish-highlighter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run build
        working-directory: packages/highlighter
      - run: npm publish
        working-directory: packages/highlighter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-editor:
    needs: publish-highlighter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run build
        working-directory: packages/editor
      - run: npm publish
        working-directory: packages/editor
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
